# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76c8efb704eefb7a047f6c59b29c0c820bfab9dbb93bae75008d192d8024c4232fc62fffff06d80b1827f5df7105e825fa3256f4d27a91f71325bedbfce0e71c

test:
  secret_key_base: 82956969bf70c345977bac2b1ec0d8502712c51ef0f04b31b87147d0989f49b8d4f3249a0b83a936b0e56ac9fbb5a39a70be3e895a1614e9cd8f62a2f5781ac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
